FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block neutron_zvm_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}


{% set neutron_zvm_agent_pip_packages = [
    '-egit+https://github.com/openstack/networking-zvm@master#egg=neutron'
] %}

RUN {{ macros.install_pip(neutron_zvm_agent_pip_packages | customizable("pip_packages")) }}

RUN cp -r /plugins/neutron-zvm-plugin-10.0.1.dev3/neutron/plugins/* /var/lib/kolla/venv/lib/python2.7/site-packages/neutron/plugins

COPY token.dat /etc/zvmsdk
RUN chmod 755 /etc/zvmsdk/token.dat

{% block neutron_server_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
